### ISSUE TITLE
initialization: init all subsystems before checking for failure

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.firmware.c#14]
Previously, Version 2 initialized all subsystems and set a unique flag for any subsystem that failed. After all initializations were attempted the cumulative result was evaluated.
This permits a tag to continue to operate even if one subsystem cannot be initialized or causes a hangup.
The only peripheral subsystem that must be successfully initialized and operational is BLE (and a RTC which It depends on) since if the tag is being used as a proximity beacon, sensors are not necessary. Additionally failure of the accelerator to initialize may not be important in a "old-chain" application.

**Comment by ojousima** [comment]
The latest error check logic has two cases: fatal and non-fatal errors. Fatal error is something that is considered non-recoverable and device tries to enter bootloader afterwards. 

Non-fatal errors leave a global flag which can be checked separately before entering main loop. Personally I see three different cases for error:
* Fatal: current firmware will fail in unpredictable ways, enter bootloader and hope tag will recover.
* Non-fatal, end-user: Tag can operate with limited functionality, broadcast limited data such as RAWv2 with accelration invalid. Covered by current logic. 
* Non-fatal, quality control: QC operator can check the error with wired debugger if it is not obvious from sensor data. 

If something causes the application to crash for example on accelerometer not found rather than logging a warning it's a bug and I'll fix it.

**Comment by ojousima** [comment]
Closing.
