### ISSUE TITLE
Mesh

### ISSUE THREAD

**Issue by phaethon** [ruuvi/ruuvi.firmware.c#333]
Is it planned to implement BLE mesh? My use case scenario is - I have several Ruuvi Tags with overlapping ranges, but from my phone I can reach only one device, but I want to read data from all.

**Comment by ojousima** [comment]
Hello,

We're not planning to implement Bluetooth Mesh because configuring the network would add complexity and might lead to unpredictable battery drain unless tags are configured as low-power nodes. 

Ruuvi Gateway has a lot better reception than most phones, it might solve your need. 

For commercial deployments Miramesh, Wirepas and Fruity Mesh can be used, the companies can run their mesh on RuuviTags.
